library(lubridate)
library(dplyr)
data<-read.table("household_power_consumption.txt",sep=";",header = TRUE)
data$Date<-dmy(data$Date)
subdata<-subset(data,Date == ymd("2007-2-1")|Date == ymd("2007-2-2"))
subdata$Global_active_power<-as.numeric(as.character(subdata$Global_active_power))
subdata<-subdata%>% mutate(TD = as.POSIXct(paste(Date,Time),format="%Y-%m-%d %H:%M:%S") )
png("plot2.png", height = 480, width = 480)
plot(subdata$Global_active_power~subdata$TD,type="l",xlab = "Global Active Power (kilowatts)")
dev.off()
